# Generated by Django 2.2.24 on 2021-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("ordersapp", "0002_auto_20211212_2136"),
=======
        ('ordersapp', '0002_auto_20211212_2136'),
>>>>>>> 3a9bad6716dba8f084b937e336558da48567edcf
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="order",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="активен"),
=======
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активен'),
>>>>>>> 3a9bad6716dba8f084b937e336558da48567edcf
        ),
    ]
